# Setup
title:            Franco Chalissery
tagline:          'To Franco Chalissery'
description:      '<a href="https://jekyllrb.com" target="_blank">Jekyll</a> <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              https://ca-franco.github.io
baseurl:          ''
paginate:         5

# About and contact
author:
  name:           'Franco Chalissery'
  url:            https://twitter.com/fchaliss

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          3.0.0
