# Setup
title:            Franco's
tagline:          'To Franco Chalissery'
description:      'Programming blog'
url:              https://ca-franco.github.io
baseurl:          ''
paginate:         5
linkedin:         https://www.linkedin.com/in/francochalissery/

# About and contact
author:
  name:           'Franco Chalissery'
  url:            https://twitter.com/fchaliss

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          3.0.0
